export interface AHSPComponentItem {
  kategori: 'UPAH' | 'BAHAN' | 'ALAT';
  uraian: string;
  satuan: string;
  koefisien: number;
  hargaDasar: number;
  jumlah: number;
}

export interface Berkas002AHSPItem {
  id: string;
  kode: string;
  namaPekerjaan: string;
  satuanPekerjaan: string;
  divisi: string;
  romawi: string;
  totalUpah: number;
  totalBahan: number;
  totalAlat: number;
  hargaSatuan: number;
  komponen: AHSPComponentItem[];
}

export const BERKAS_002_AHSP_DATA: Berkas002AHSPItem[] = [
  {
    id: 'ahsp-a3',
    kode: 'A.3',
    namaPekerjaan: 'Pengukuran Lapangan & Pemasangan Bowplank Kayu',
    satuanPekerjaan: 'm1',
    divisi: 'PEKERJAAN PERSIAPAN',
    romawi: 'I',
    totalUpah: 20000,
    totalBahan: 22500,
    totalAlat: 0,
    hargaSatuan: 42500,
    komponen: [
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.10, hargaDasar: 110000, jumlah: 11000 },
      { kategori: 'UPAH', uraian: 'Tukang Kayu', satuan: 'OH', koefisien: 0.05, hargaDasar: 140000, jumlah: 7000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.01, hargaDasar: 155000, jumlah: 1550 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.003, hargaDasar: 150000, jumlah: 450 },
      { kategori: 'BAHAN', uraian: 'Kayu Usuk 5/7 Kelas III', satuan: 'm3', koefisien: 0.012, hargaDasar: 1500000, jumlah: 18000 },
      { kategori: 'BAHAN', uraian: 'Paku Biasa 2"-5"', satuan: 'kg', koefisien: 0.02, hargaDasar: 22500, jumlah: 450 },
      { kategori: 'BAHAN', uraian: 'Kayu Papan 2/20 Sengon/Randu', satuan: 'm3', koefisien: 0.007, hargaDasar: 1400000, jumlah: 4050 },
    ],
  },
  {
    id: 'ahsp-b1',
    kode: 'B.1',
    namaPekerjaan: 'Galian Tanah Pondasi Menerus & Pondasi Telapak (Kedalaman s/d 1 m)',
    satuanPekerjaan: 'm3',
    divisi: 'PEKERJAAN TANAH DAN PASIR',
    romawi: 'II',
    totalUpah: 115000,
    totalBahan: 0,
    totalAlat: 0,
    hargaSatuan: 115000,
    komponen: [
      { kategori: 'UPAH', uraian: 'Pekerja Terlatih', satuan: 'OH', koefisien: 0.75, hargaDasar: 110000, jumlah: 82500 },
      { kategori: 'UPAH', uraian: 'Mandor Lapangan', satuan: 'OH', koefisien: 0.025, hargaDasar: 150000, jumlah: 3750 },
      { kategori: 'UPAH', uraian: 'Tukang Gali', satuan: 'OH', koefisien: 0.20, hargaDasar: 140000, jumlah: 28000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.005, hargaDasar: 150000, jumlah: 750 },
    ],
  },
  {
    id: 'ahsp-b2',
    kode: 'B.2',
    namaPekerjaan: 'Urugan Pasir Bawah Pondasi Tebal 5 cm Padat',
    satuanPekerjaan: 'm3',
    divisi: 'PEKERJAAN TANAH DAN PASIR',
    romawi: 'II',
    totalUpah: 38000,
    totalBahan: 222000,
    totalAlat: 0,
    hargaSatuan: 260000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Pasir Urug Alam Bersih', satuan: 'm3', koefisien: 1.20, hargaDasar: 185000, jumlah: 222000 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.30, hargaDasar: 110000, jumlah: 33000 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.03, hargaDasar: 150000, jumlah: 4500 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.003, hargaDasar: 166667, jumlah: 500 },
    ],
  },
  {
    id: 'ahsp-c1',
    kode: 'C.1',
    namaPekerjaan: 'Pasangan Pondasi Batu Belah Campuran 1 PC : 5 PP',
    satuanPekerjaan: 'm3',
    divisi: 'PEKERJAAN PONDASI DAN STRUKTUR BETON BERTULANG',
    romawi: 'III',
    totalUpah: 360000,
    totalBahan: 790000,
    totalAlat: 0,
    hargaSatuan: 1150000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Batu Belah Gunung 15/20 cm', satuan: 'm3', koefisien: 1.20, hargaDasar: 260000, jumlah: 312000 },
      { kategori: 'BAHAN', uraian: 'Semen Portland (PC 50kg)', satuan: 'kg', koefisien: 136.0, hargaDasar: 1600, jumlah: 217600 },
      { kategori: 'BAHAN', uraian: 'Pasir Pasang Kali', satuan: 'm3', koefisien: 0.544, hargaDasar: 290000, jumlah: 157760 },
      { kategori: 'BAHAN', uraian: 'Air Kerja Bersih', satuan: 'liter', koefisien: 200, hargaDasar: 513.2, jumlah: 102640 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 1.50, hargaDasar: 110000, jumlah: 165000 },
      { kategori: 'UPAH', uraian: 'Tukang Batu', satuan: 'OH', koefisien: 0.75, hargaDasar: 140000, jumlah: 105000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.075, hargaDasar: 155000, jumlah: 11625 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.075, hargaDasar: 150000, jumlah: 11250 },
      { kategori: 'UPAH', uraian: 'Operator / Tenaga Bantu', satuan: 'OH', koefisien: 0.45, hargaDasar: 150000, jumlah: 67125 },
    ],
  },
  {
    id: 'ahsp-c2',
    kode: 'C.2',
    namaPekerjaan: 'Beton Sloof 15/20 cm Mutu f\'c 14.5 MPa (K-175)',
    satuanPekerjaan: 'm3',
    divisi: 'PEKERJAAN PONDASI DAN STRUKTUR BETON BERTULANG',
    romawi: 'III',
    totalUpah: 380000,
    totalBahan: 1070000,
    totalAlat: 0,
    hargaSatuan: 1450000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Semen Portland (PC) SNI', satuan: 'kg', koefisien: 326.0, hargaDasar: 1600, jumlah: 521600 },
      { kategori: 'BAHAN', uraian: 'Pasir Beton / Cor Bersih', satuan: 'kg', koefisien: 760.0, hargaDasar: 320, jumlah: 243200 },
      { kategori: 'BAHAN', uraian: 'Batu Split / Kerikil Cor 2/3 cm', satuan: 'kg', koefisien: 1029.0, hargaDasar: 280, jumlah: 288120 },
      { kategori: 'BAHAN', uraian: 'Air Kerja Campuran', satuan: 'liter', koefisien: 215, hargaDasar: 79.4, jumlah: 17080 },
      { kategori: 'UPAH', uraian: 'Pekerja Cor', satuan: 'OH', koefisien: 1.65, hargaDasar: 110000, jumlah: 181500 },
      { kategori: 'UPAH', uraian: 'Tukang Batu / Cor', satuan: 'OH', koefisien: 0.275, hargaDasar: 140000, jumlah: 38500 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.028, hargaDasar: 155000, jumlah: 4340 },
      { kategori: 'UPAH', uraian: 'Mandor Lapangan', satuan: 'OH', koefisien: 0.083, hargaDasar: 150000, jumlah: 12450 },
      { kategori: 'UPAH', uraian: 'Operator Molen Beton', satuan: 'OH', koefisien: 0.95, hargaDasar: 150747, jumlah: 143210 },
    ],
  },
  {
    id: 'ahsp-c3',
    kode: 'C.3',
    namaPekerjaan: 'Pembesian Sloof Besi Beton Polos / Ulir SNI',
    satuanPekerjaan: 'kg',
    divisi: 'PEKERJAAN PONDASI DAN STRUKTUR BETON BERTULANG',
    romawi: 'III',
    totalUpah: 2800,
    totalBahan: 13700,
    totalAlat: 0,
    hargaSatuan: 16500,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Besi Beton Polos / Ulir SNI', satuan: 'kg', koefisien: 1.05, hargaDasar: 12300, jumlah: 12915 },
      { kategori: 'BAHAN', uraian: 'Kawat Beton / Bendrat SNI', satuan: 'kg', koefisien: 0.025, hargaDasar: 31400, jumlah: 785 },
      { kategori: 'UPAH', uraian: 'Pekerja Besi', satuan: 'OH', koefisien: 0.007, hargaDasar: 110000, jumlah: 770 },
      { kategori: 'UPAH', uraian: 'Tukang Besi', satuan: 'OH', koefisien: 0.007, hargaDasar: 140000, jumlah: 980 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.0007, hargaDasar: 155000, jumlah: 108.5 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.0004, hargaDasar: 150000, jumlah: 60 },
      { kategori: 'UPAH', uraian: 'Penekuk & Pemotong Besi', satuan: 'OH', koefisien: 0.006, hargaDasar: 146917, jumlah: 881.5 },
    ],
  },
  {
    id: 'ahsp-c4',
    kode: 'C.4',
    namaPekerjaan: 'Pasang Bekisting Sloof dengan Papan Kayu Kelas III',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN PONDASI DAN STRUKTUR BETON BERTULANG',
    romawi: 'III',
    totalUpah: 65000,
    totalBahan: 120000,
    totalAlat: 0,
    hargaSatuan: 185000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Kayu Terentang / Papan Cor 2/20', satuan: 'm3', koefisien: 0.045, hargaDasar: 2100000, jumlah: 94500 },
      { kategori: 'BAHAN', uraian: 'Paku Biasa 2"- 5"', satuan: 'kg', koefisien: 0.30, hargaDasar: 22000, jumlah: 6600 },
      { kategori: 'BAHAN', uraian: 'Minyak Bekisting Pelumas', satuan: 'liter', koefisien: 0.10, hargaDasar: 25000, jumlah: 2500 },
      { kategori: 'BAHAN', uraian: 'Balok Kayu Penyangga 5/7', satuan: 'm3', koefisien: 0.008, hargaDasar: 2050000, jumlah: 16400 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.26, hargaDasar: 110000, jumlah: 28600 },
      { kategori: 'UPAH', uraian: 'Tukang Kayu', satuan: 'OH', koefisien: 0.13, hargaDasar: 140000, jumlah: 18200 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.026, hargaDasar: 155000, jumlah: 4030 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.013, hargaDasar: 150000, jumlah: 1950 },
      { kategori: 'UPAH', uraian: 'Tenaga Bongkar Bekisting', satuan: 'OH', koefisien: 0.08, hargaDasar: 152750, jumlah: 12220 },
    ],
  },
  {
    id: 'ahsp-d1',
    kode: 'D.1',
    namaPekerjaan: 'Pasangan Dinding Bata Ringan (Hebel) t = 10 cm + Perekat Mortar',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN DINDING, PLESTERAN & ACIAN',
    romawi: 'IV',
    totalUpah: 52000,
    totalBahan: 93000,
    totalAlat: 0,
    hargaSatuan: 145000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Bata Ringan (AAC / Hebel) t=10cm', satuan: 'm3', koefisien: 0.10, hargaDasar: 680000, jumlah: 68000 },
      { kategori: 'BAHAN', uraian: 'Semen Thinbed Mortar Perekat Hebel (40kg)', satuan: 'kg', koefisien: 4.0, hargaDasar: 2400, jumlah: 9600 },
      { kategori: 'BAHAN', uraian: 'Air Bersih Adukan', satuan: 'liter', koefisien: 10, hargaDasar: 500, jumlah: 5000 },
      { kategori: 'BAHAN', uraian: 'Besi Strip Pengikat / Angkur', satuan: 'bh', koefisien: 1.5, hargaDasar: 6933, jumlah: 10400 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.20, hargaDasar: 110000, jumlah: 22000 },
      { kategori: 'UPAH', uraian: 'Tukang Pasang Bata Ringan', satuan: 'OH', koefisien: 0.15, hargaDasar: 140000, jumlah: 21000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.015, hargaDasar: 155000, jumlah: 2325 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.01, hargaDasar: 150000, jumlah: 1500 },
      { kategori: 'UPAH', uraian: 'Tenaga Angkut & Langsir', satuan: 'OH', koefisien: 0.035, hargaDasar: 147857, jumlah: 5175 },
    ],
  },
  {
    id: 'ahsp-d2',
    kode: 'D.2',
    namaPekerjaan: 'Plesteran Dinding Adukan 1 : 4 tebal 15 mm',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN DINDING, PLESTERAN & ACIAN',
    romawi: 'IV',
    totalUpah: 41000,
    totalBahan: 31000,
    totalAlat: 0,
    hargaSatuan: 72000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Semen PC (Portland Cement)', satuan: 'kg', koefisien: 6.24, hargaDasar: 1600, jumlah: 9984 },
      { kategori: 'BAHAN', uraian: 'Pasir Pasang Halus Terayak', satuan: 'm3', koefisien: 0.024, hargaDasar: 320000, jumlah: 7680 },
      { kategori: 'BAHAN', uraian: 'Air Bersih Plesteran', satuan: 'liter', koefisien: 12, hargaDasar: 1111.3, jumlah: 13336 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.20, hargaDasar: 110000, jumlah: 22000 },
      { kategori: 'UPAH', uraian: 'Tukang Plester', satuan: 'OH', koefisien: 0.10, hargaDasar: 140000, jumlah: 14000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.01, hargaDasar: 155000, jumlah: 1550 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.01, hargaDasar: 150000, jumlah: 1500 },
      { kategori: 'UPAH', uraian: 'Tenaga Ayak & Siram Dinding', satuan: 'OH', koefisien: 0.013, hargaDasar: 150000, jumlah: 1950 },
    ],
  },
  {
    id: 'ahsp-d3',
    kode: 'D.3',
    namaPekerjaan: 'Acian Dinding Semen Instan / PC Halus',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN DINDING, PLESTERAN & ACIAN',
    romawi: 'IV',
    totalUpah: 23000,
    totalBahan: 15000,
    totalAlat: 0,
    hargaSatuan: 38000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Semen Acian Instan / Mortar Skimcoat', satuan: 'kg', koefisien: 3.25, hargaDasar: 2800, jumlah: 9100 },
      { kategori: 'BAHAN', uraian: 'Air Bersih & Kertas Amplas Halus', satuan: 'Ls', koefisien: 1, hargaDasar: 5900, jumlah: 5900 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.10, hargaDasar: 110000, jumlah: 11000 },
      { kategori: 'UPAH', uraian: 'Tukang Acian', satuan: 'OH', koefisien: 0.07, hargaDasar: 140000, jumlah: 9800 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.007, hargaDasar: 155000, jumlah: 1085 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.005, hargaDasar: 150000, jumlah: 750 },
      { kategori: 'UPAH', uraian: 'Tenaga Halus & Gosok', satuan: 'OH', koefisien: 0.002, hargaDasar: 182500, jumlah: 365 },
    ],
  },
  {
    id: 'ahsp-f1',
    kode: 'F.1',
    namaPekerjaan: 'Rangka Kuda-Kuda Atap Baja Ringan Kanal C.75 t=0.75 mm SNI',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN RANGKA & PENUTUP ATAP',
    romawi: 'VI',
    totalUpah: 45000,
    totalBahan: 130000,
    totalAlat: 0,
    hargaSatuan: 175000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Baja Ringan Kanal C75 t=0.75 mm SNI (6 m)', satuan: 'btg', koefisien: 0.95, hargaDasar: 115000, jumlah: 109250 },
      { kategori: 'BAHAN', uraian: 'Baut Screw Drilling Truss Hex 10x19', satuan: 'bh', koefisien: 14, hargaDasar: 450, jumlah: 6300 },
      { kategori: 'BAHAN', uraian: 'Dynabolt M10x65 Anchor Bolt', satuan: 'bh', koefisien: 0.8, hargaDasar: 4500, jumlah: 3600 },
      { kategori: 'BAHAN', uraian: 'Braket L Pelat Pengaku Baja', satuan: 'bh', koefisien: 0.6, hargaDasar: 18083, jumlah: 10850 },
      { kategori: 'UPAH', uraian: 'Pekerja Pembantu', satuan: 'OH', koefisien: 0.12, hargaDasar: 110000, jumlah: 13200 },
      { kategori: 'UPAH', uraian: 'Tukang Pasang Rangka Baja Ringan', satuan: 'OH', koefisien: 0.18, hargaDasar: 145000, jumlah: 26100 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.018, hargaDasar: 160000, jumlah: 2880 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.012, hargaDasar: 150000, jumlah: 1800 },
      { kategori: 'UPAH', uraian: 'Tenaga Kalibrasi Waterpass & Elevasi', satuan: 'OH', koefisien: 0.007, hargaDasar: 145714, jumlah: 1020 },
    ],
  },
  {
    id: 'ahsp-f3',
    kode: 'F.3',
    namaPekerjaan: 'Penutup Atap Genteng Metal Berpasir tebal 0.35 mm',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN RANGKA & PENUTUP ATAP',
    romawi: 'VI',
    totalUpah: 32000,
    totalBahan: 103000,
    totalAlat: 0,
    hargaSatuan: 135000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Genteng Metal Berpasir 2x4 Daun t=0.35 mm', satuan: 'lbr', koefisien: 1.62, hargaDasar: 56000, jumlah: 90720 },
      { kategori: 'BAHAN', uraian: 'Roof Screw Reng Genteng Metal', satuan: 'bh', koefisien: 12, hargaDasar: 400, jumlah: 4800 },
      { kategori: 'BAHAN', uraian: 'Sealant Waterproofing & Cat Sentuh', satuan: 'Ls', koefisien: 1, hargaDasar: 7480, jumlah: 7480 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.12, hargaDasar: 110000, jumlah: 13200 },
      { kategori: 'UPAH', uraian: 'Tukang Pasang Atap Metal', satuan: 'OH', koefisien: 0.10, hargaDasar: 140000, jumlah: 14000 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.01, hargaDasar: 155000, jumlah: 1550 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.01, hargaDasar: 150000, jumlah: 1500 },
      { kategori: 'UPAH', uraian: 'Tenaga Langsir & Pengaman Atap', satuan: 'OH', koefisien: 0.012, hargaDasar: 145833, jumlah: 1750 },
    ],
  },
  {
    id: 'ahsp-g2',
    kode: 'G.2',
    namaPekerjaan: 'Penutup Plafon PVC Tebal 8 mm Motif Serat Kayu Minimalis',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN PLAFON / LANGIT-LANGIT',
    romawi: 'VII',
    totalUpah: 45000,
    totalBahan: 110000,
    totalAlat: 0,
    hargaSatuan: 155000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Papan Plafon PVC t=8 mm L=20 cm', satuan: 'm1', koefisien: 5.10, hargaDasar: 19500, jumlah: 99450 },
      { kategori: 'BAHAN', uraian: 'Baut Sekrup Plafon PVC Kepala Pipih', satuan: 'bh', koefisien: 16, hargaDasar: 250, jumlah: 4000 },
      { kategori: 'BAHAN', uraian: 'Lis Sambung H / Sudut PVC', satuan: 'm1', koefisien: 0.25, hargaDasar: 26200, jumlah: 6550 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.15, hargaDasar: 110000, jumlah: 16500 },
      { kategori: 'UPAH', uraian: 'Tukang Plafon PVC', satuan: 'OH', koefisien: 0.16, hargaDasar: 140000, jumlah: 22400 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.016, hargaDasar: 155000, jumlah: 2480 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.01, hargaDasar: 150000, jumlah: 1500 },
      { kategori: 'UPAH', uraian: 'Tenaga Penyetelan Nat Rapi', satuan: 'OH', koefisien: 0.014, hargaDasar: 151428, jumlah: 2120 },
    ],
  },
  {
    id: 'ahsp-h3',
    kode: 'H.3',
    namaPekerjaan: 'Pasangan Lantai Granit Tile 60x60 cm Polish Homogenous',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN LANTAI & KERAMIK',
    romawi: 'VIII',
    totalUpah: 75000,
    totalBahan: 210000,
    totalAlat: 0,
    hargaSatuan: 285000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Granit Tile Homogenous Polish 60x60 cm Single Loading', satuan: 'm2', koefisien: 1.05, hargaDasar: 165000, jumlah: 173250 },
      { kategori: 'BAHAN', uraian: 'Semen Instan Perekat Granit Tile (Thinbed Granit)', satuan: 'kg', koefisien: 5.0, hargaDasar: 3800, jumlah: 19000 },
      { kategori: 'BAHAN', uraian: 'Semen Pengisi Nat Tile Grout Warna Anti Jamur', satuan: 'kg', koefisien: 0.65, hargaDasar: 18500, jumlah: 12025 },
      { kategori: 'BAHAN', uraian: 'Spacer Silang Nat 2 mm & Pembersih', satuan: 'Ls', koefisien: 1, hargaDasar: 5725, jumlah: 5725 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.25, hargaDasar: 110000, jumlah: 27500 },
      { kategori: 'UPAH', uraian: 'Tukang Granit Khusus', satuan: 'OH', koefisien: 0.28, hargaDasar: 145000, jumlah: 40600 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.028, hargaDasar: 160000, jumlah: 4480 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.015, hargaDasar: 150000, jumlah: 2250 },
      { kategori: 'UPAH', uraian: 'Tenaga Pengisian Nat & Pembersihan Granit', satuan: 'OH', koefisien: 0.001, hargaDasar: 170000, jumlah: 170 },
    ],
  },
  {
    id: 'ahsp-i1',
    kode: 'I.1',
    namaPekerjaan: 'Pengecatan Tembok Dinding Interior 3 Lapis (Plamir + Cat Dasar + Akhir)',
    satuanPekerjaan: 'm2',
    divisi: 'PEKERJAAN PENGECATAN',
    romawi: 'IX',
    totalUpah: 16000,
    totalBahan: 20000,
    totalAlat: 0,
    hargaSatuan: 36000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Plamir Tembok Siap Pakai', satuan: 'kg', koefisien: 0.12, hargaDasar: 18000, jumlah: 2160 },
      { kategori: 'BAHAN', uraian: 'Cat Dasar Alkali Sealer Dinding', satuan: 'kg', koefisien: 0.10, hargaDasar: 42000, jumlah: 4200 },
      { kategori: 'BAHAN', uraian: 'Cat Tembok Interior Emulsi (2 Lapis)', satuan: 'kg', koefisien: 0.26, hargaDasar: 45000, jumlah: 11700 },
      { kategori: 'BAHAN', uraian: 'Kertas Gosok / Amplas No. 120 & Masking Tape', satuan: 'lbr', koefisien: 0.35, hargaDasar: 5542, jumlah: 1940 },
      { kategori: 'UPAH', uraian: 'Pekerja', satuan: 'OH', koefisien: 0.04, hargaDasar: 110000, jumlah: 4400 },
      { kategori: 'UPAH', uraian: 'Tukang Cat', satuan: 'OH', koefisien: 0.07, hargaDasar: 140000, jumlah: 9800 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.007, hargaDasar: 155000, jumlah: 1085 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.003, hargaDasar: 150000, jumlah: 450 },
      { kategori: 'UPAH', uraian: 'Tenaga Perlindungan Lantai & Isolasi', satuan: 'OH', koefisien: 0.002, hargaDasar: 132500, jumlah: 265 },
    ],
  },
  {
    id: 'ahsp-j1',
    kode: 'J.1',
    namaPekerjaan: 'Titik Instalasi Penerangan Lampu Kabel NYM 3x2.5 mm dlm Conduit High Impact',
    satuanPekerjaan: 'Titik',
    divisi: 'PEKERJAAN ELEKTRIKAL & PENERANGAN',
    romawi: 'X',
    totalUpah: 85000,
    totalBahan: 155000,
    totalAlat: 0,
    hargaSatuan: 240000,
    komponen: [
      { kategori: 'BAHAN', uraian: 'Kabel Listrik NYM 3 x 2.5 mm2 SNI LMK', satuan: 'm1', koefisien: 12.0, hargaDasar: 9800, jumlah: 117600 },
      { kategori: 'BAHAN', uraian: 'Pipa Conduit PVC High Impact 20 mm + Klem', satuan: 'btg', koefisien: 2.5, hargaDasar: 9500, jumlah: 23750 },
      { kategori: 'BAHAN', uraian: 'T-Dus Cabang 3/4 & Inbow Dus Mangkok', satuan: 'bh', koefisien: 2.0, hargaDasar: 4200, jumlah: 8400 },
      { kategori: 'BAHAN', uraian: 'Isolasi Listrik PVC Heavy Duty & Lasdop', satuan: 'Ls', koefisien: 1, hargaDasar: 5250, jumlah: 5250 },
      { kategori: 'UPAH', uraian: 'Pembantu Tukang Listrik', satuan: 'OH', koefisien: 0.25, hargaDasar: 110000, jumlah: 27500 },
      { kategori: 'UPAH', uraian: 'Tukang Instalatur Listrik Berlisensi', satuan: 'OH', koefisien: 0.35, hargaDasar: 145000, jumlah: 50750 },
      { kategori: 'UPAH', uraian: 'Kepala Tukang', satuan: 'OH', koefisien: 0.03, hargaDasar: 160000, jumlah: 4800 },
      { kategori: 'UPAH', uraian: 'Mandor', satuan: 'OH', koefisien: 0.01, hargaDasar: 150000, jumlah: 1500 },
      { kategori: 'UPAH', uraian: 'Tenaga Tes Kontinuitas & Meggering', satuan: 'OH', koefisien: 0.003, hargaDasar: 150000, jumlah: 450 },
    ],
  },
];

export function getBerkas002FlatBOMRows(): {
  kodeAnalisa: string;
  namaPekerjaan: string;
  tipe: 'BAHAN' | 'UPAH' | 'ALAT';
  uraianKomponen: string;
  koefisien: number;
  satuan: string;
  hargaDasar: number;
  jumlah: number;
}[] {
  const result: any[] = [];
  BERKAS_002_AHSP_DATA.forEach((item) => {
    item.komponen.forEach((k) => {
      result.push({
        kodeAnalisa: item.kode,
        namaPekerjaan: item.namaPekerjaan,
        tipe: k.kategori,
        uraianKomponen: k.uraian,
        koefisien: k.koefisien,
        satuan: k.satuan,
        hargaDasar: k.hargaDasar,
        jumlah: k.jumlah,
      });
    });
  });
  return result;
}
