import {
  CashTransaction,
  DailyWorkLog,
  Kwitansi,
  PayrollHarianBatch,
  ProjectInfo,
  WBSItem,
  WeeklyRecap,
  WorkerBoronganItem,
} from '../types';

export const isPublishedApp = (): boolean => {
  if (typeof window === 'undefined') return false;
  // If Vite build is production
  if (import.meta.env.PROD) return true;
  // If URL hostname matches published environments (ais-pre, Cloud Run, custom domain, etc.)
  const host = window.location.hostname;
  if (
    host.includes('ais-pre') ||
    (host.includes('.run.app') && !host.includes('ais-dev')) ||
    (!host.includes('localhost') && !host.includes('127.0.0.1') && !host.includes('ais-dev'))
  ) {
    return true;
  }
  return false;
};

export const CLEAN_PROJECT_INFO: ProjectInfo = {
  namaProyek: 'Program Revitalisasi Sarana Prasarana Sekolah P2SP',
  nomorSuratTugas: '',
  lokasi: '',
  desa: '',
  kecamatan: '',
  kabupaten: '',
  provinsi: 'Jawa Barat',
  tahunAnggaran: '2026',
  totalPaguAnggaran: 0,
  namaInstansi: 'Tim P2SP Revitalisasi Sekolah',
  namaKetuaTPK: '',
  namaBendahara: '',
  namaPelaksanaTeknis: '',
  namaPimpinan: '',
  namaBank: '',
  nomorRekeningBank: '',
  atasNamaRekening: '',
  targetMulai: '',
  targetSelesai: '',
  dataSekolah: {
    namaSekolah: 'Sekolah Pelaksana Revitalisasi',
    npsn: '20260001',
    jenjang: 'SD',
    statusSekolah: 'NEGERI',
    nomorSkP2sp: '',
    tanggalSkP2sp: '',
  },
  alamatLengkap: {
    jalan: '',
    rtRw: '',
    desaKelurahan: '',
    kecamatan: '',
    kabupatenKota: '',
    provinsi: 'Jawa Barat',
    kodePos: '',
  },
  timP2sp: {
    penanggungJawab: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Kepala Sekolah',
      noHp: '',
      alamat: '',
    },
    ketuaP2sp: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Ketua Komite Sekolah',
      noHp: '',
      alamat: '',
    },
    sekretarisLogistik: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Guru / Pengelola Sarpras',
      noHp: '',
      alamat: '',
    },
    bendahara: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Bendahara Sekolah / BOS',
      noHp: '',
      alamat: '',
    },
    kepalaPelaksana: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Kepala Pelaksana Konstruksi',
      noHp: '',
      alamat: '',
    },
    keamanan: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Petugas Keamanan',
      noHp: '',
      alamat: '',
    },
    perencana: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Perencana Teknis (RAB & Gambar)',
      noHp: '',
      alamat: '',
    },
    pengawas: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Pengawas Teknis Lapangan',
      noHp: '',
      alamat: '',
    },
    fasilitator: {
      nama: '',
      nipNik: '',
      jabatanAsal: 'Fasilitator Teknis / Pendamping Dinas',
      noHp: '',
      alamat: '',
    },
  },
};

export const INITIAL_PROJECT_INFO: ProjectInfo = {
  namaProyek: 'Revitalisasi Ruang Kelas & Sarana Prasarana Sekolah SDN 01 Babakan',
  nomorSuratTugas: '421.2/015/P2SP-SDN01/2026',
  lokasi: 'Jl. Raya Babakan No. 42, RT 02 / RW 04',
  desa: 'Babakan',
  kecamatan: 'Babakan Madang',
  kabupaten: 'Bogor',
  provinsi: 'Jawa Barat',
  tahunAnggaran: '2026',
  totalPaguAnggaran: 185000000,
  namaInstansi: 'SDN 01 Babakan (Tim P2SP Revitalisasi)',
  namaKetuaTPK: 'H. Rahmat Hidayat, S.T.',
  namaBendahara: 'Siti Nurhalizah, S.E.',
  namaPelaksanaTeknis: 'Drs. Agus Sulaeman',
  namaPimpinan: 'Dra. Hj. Endang Rahayu, M.Pd.',
  namaBank: 'Bank BJB Cabang Cibinong',
  nomorRekeningBank: '0087-2311-2990-1',
  atasNamaRekening: 'P2SP SDN 01 BABAKAN',
  targetMulai: '2026-02-01',
  targetSelesai: '2026-05-31',
  // Master Data Sekolah
  dataSekolah: {
    namaSekolah: 'SD Negeri 01 Babakan',
    npsn: '20201842',
    jenjang: 'SD',
    statusSekolah: 'NEGERI',
    nomorSkP2sp: '421.2/015/P2SP-SDN01/2026',
    tanggalSkP2sp: '2026-01-15',
  },
  // Alamat Lengkap
  alamatLengkap: {
    jalan: 'Jl. Raya Babakan No. 42, Dusun Babakan Kaum',
    rtRw: 'RT 02 / RW 04',
    desaKelurahan: 'Babakan',
    kecamatan: 'Babakan Madang',
    kabupatenKota: 'Kabupaten Bogor',
    provinsi: 'Jawa Barat',
    kodePos: '16810',
  },
  // Susunan Lengkap Tim Pelaksana P2SP (9 Peran Resmi)
  timP2sp: {
    penanggungJawab: {
      nama: 'Dra. Hj. Endang Rahayu, M.Pd.',
      nipNik: '19740512 199803 2 004',
      jabatanAsal: 'Kepala Sekolah',
      noHp: '0812-8877-6651',
      alamat: 'Komplek Griya Babakan Asri No. 12',
    },
    ketuaP2sp: {
      nama: 'H. Rahmat Hidayat, S.T.',
      nipNik: '3201081504780003',
      jabatanAsal: 'Ketua Komite Sekolah',
      noHp: '0813-1122-3344',
      alamat: 'Kp. Babakan Tengah RT 01/RW 03',
    },
    sekretarisLogistik: {
      nama: 'Muhammad Rizki Fauzi, S.Pd.',
      nipNik: '19890214 201903 1 008',
      jabatanAsal: 'Guru & Pengelola Sarpras',
      noHp: '0857-1234-5678',
      alamat: 'Perum Grand Babakan Indah Blok C-5',
    },
    bendahara: {
      nama: 'Siti Nurhalizah, S.E.',
      nipNik: '3201085208850002',
      jabatanAsal: 'Bendahara Sekolah / BOS',
      noHp: '0821-9988-7766',
      alamat: 'Jl. Melati No. 8, Desa Babakan',
    },
    kepalaPelaksana: {
      nama: 'Drs. Agus Sulaeman',
      nipNik: '3201082207700001',
      jabatanAsal: 'Kepala Pelaksana / Mandor Konstruksi',
      noHp: '0815-7788-9900',
      alamat: 'Kp. Pasir Maung RT 03/RW 02',
    },
    keamanan: {
      nama: 'Suparman Wijaya',
      nipNik: '3201080905750004',
      jabatanAsal: 'Petugas Keamanan & Kamtib Lingkungan',
      noHp: '0858-6677-8899',
      alamat: 'Kp. Babakan Hilir RT 04/RW 01',
    },
    perencana: {
      nama: 'Ir. Hendra Gunawan, M.T.',
      nipNik: '3271031406800007',
      jabatanAsal: 'Perencana Teknis (Gambar & RAB)',
      noHp: '0811-2233-4455',
      alamat: 'Jl. Raya Pajajaran No. 88, Bogor',
    },
    pengawas: {
      nama: 'Budi Santoso, S.T.',
      nipNik: '3201081109830005',
      jabatanAsal: 'Pengawas Teknis Lapangan',
      noHp: '0812-3456-7890',
      alamat: 'Perum Sentul Valley Blok D-11',
    },
    fasilitator: {
      nama: 'Ir. Ahmad Zarkasih, M.Eng.',
      nipNik: '19800615 200801 1 012',
      jabatanAsal: 'Fasilitator Teknis / Pendamping Dinas',
      noHp: '0813-4567-8901',
      alamat: 'Jl. Tegar Beriman No. 45, Cibinong',
    },
  },
};

export const INITIAL_WBS: WBSItem[] = [
  {
    id: 'wbs-1',
    kode: '01.00',
    namaPekerjaan: 'Pekerjaan Persiapan, Pembersihan & Bongkaran Struktur Lama',
    bobotRencana: 6.0,
    progresRealisasi: 6.0,
    volumeRAB: 1,
    satuan: 'Ls',
    biayaRAB: 11100000,
    biayaRealisasi: 10850000,
  },
  {
    id: 'wbs-2',
    kode: '02.00',
    namaPekerjaan: 'Pekerjaan Tanah, Pondasi Tapak & Sloof Beton Bertulang',
    bobotRencana: 22.0,
    progresRealisasi: 22.0,
    volumeRAB: 18.5,
    satuan: 'm3',
    biayaRAB: 40700000,
    biayaRealisasi: 39950000,
  },
  {
    id: 'wbs-3',
    kode: '03.00',
    namaPekerjaan: 'Pekerjaan Kolom, Balok Ring & Dinding Bata Ringan (Hebel)',
    bobotRencana: 24.0,
    progresRealisasi: 21.5,
    volumeRAB: 240,
    satuan: 'm2',
    biayaRAB: 44400000,
    biayaRealisasi: 38200000,
  },
  {
    id: 'wbs-4',
    kode: '04.00',
    namaPekerjaan: 'Pekerjaan Rangka Atap Baja Ringan & Penutup Spandek Pasir',
    bobotRencana: 18.0,
    progresRealisasi: 12.0,
    volumeRAB: 185,
    satuan: 'm2',
    biayaRAB: 33300000,
    biayaRealisasi: 22500000,
  },
  {
    id: 'wbs-5',
    kode: '05.00',
    namaPekerjaan: 'Pekerjaan Lantai Granit & Saluran Drainase Keliling',
    bobotRencana: 14.0,
    progresRealisasi: 4.0,
    volumeRAB: 160,
    satuan: 'm2',
    biayaRAB: 25900000,
    biayaRealisasi: 7800000,
  },
  {
    id: 'wbs-6',
    kode: '06.00',
    namaPekerjaan: 'Pekerjaan Kusen Alumunium, Pintu Kaca & Jendela Casement',
    bobotRencana: 8.0,
    progresRealisasi: 0.0,
    volumeRAB: 14,
    satuan: 'Unit',
    biayaRAB: 14800000,
    biayaRealisasi: 0,
  },
  {
    id: 'wbs-7',
    kode: '07.00',
    namaPekerjaan: 'Pekerjaan Pengecatan Dinding Interior/Eksterior & Finishing',
    bobotRencana: 8.0,
    progresRealisasi: 0.0,
    volumeRAB: 420,
    satuan: 'm2',
    biayaRAB: 14800000,
    biayaRealisasi: 0,
  },
];

export const CLEAN_WBS: WBSItem[] = INITIAL_WBS.map((w) => ({
  ...w,
  progresRealisasi: 0,
  biayaRealisasi: 0,
}));

export const INITIAL_DAILY_LOGS: DailyWorkLog[] = [
  {
    id: 'log-01',
    tanggal: '2026-03-16',
    mingguKe: 4,
    cuaca: 'CERAH',
    jumlahTenagaKerja: { mandor: 1, tukang: 4, laden: 6 },
    uraianPekerjaan: 'Pemasangan dinding bata ringan blok B, plesteran dinding ruang depan, perakitan kuda-kuda rangka atap',
    progresHariIniPersen: 1.2,
    kendalaDanSolusi: 'Tidak ada kendala, cuaca sangat mendukung.',
    catatanMaterial: 'Semen mortar hebel masuk 40 sak dari Toko Bangunan Sumber Jaya.',
  },
  {
    id: 'log-02',
    tanggal: '2026-03-17',
    mingguKe: 4,
    cuaca: 'BERAWAN',
    jumlahTenagaKerja: { mandor: 1, tukang: 4, laden: 5 },
    uraianPekerjaan: 'Lanjutan pasangan bata ringan lantai 1, pengecoran balok praktis dan ringbalk atas',
    progresHariIniPersen: 1.0,
    kendalaDanSolusi: 'Semen instan cukup, air bersih proyek mengalir lancar.',
    catatanMaterial: 'Batu split dan pasir beton standby 1 rit.',
  },
  {
    id: 'log-03',
    tanggal: '2026-03-18',
    mingguKe: 4,
    cuaca: 'HUJAN_RINGAN',
    jumlahTenagaKerja: { mandor: 1, tukang: 3, laden: 5 },
    uraianPekerjaan: 'Pekerjaan dialihkan ke dalam ruangan: acian dinding dalam dan pembersihan area lantai',
    progresHariIniPersen: 0.7,
    kendalaDanSolusi: 'Hujan gerimis pada pukul 14:00, pengerjaan luar dihentikan dan pekerja dipindah ke bagian dalam gedung.',
    catatanMaterial: 'Baja ringan canal C75 tiba 60 batang.',
  },
  {
    id: 'log-04',
    tanggal: '2026-03-19',
    mingguKe: 4,
    cuaca: 'CERAH',
    jumlahTenagaKerja: { mandor: 1, tukang: 5, laden: 6 },
    uraianPekerjaan: 'Penaikan rangka atap baja ringan, pengelasan angkur atap, plester dinding toilet umum',
    progresHariIniPersen: 1.4,
    kendalaDanSolusi: 'Semua berjalan aman sesuai SOP K3 konstruksi.',
    catatanMaterial: 'Baut roofing dan sekrup baja ringan masuk 4 dus.',
  },
  {
    id: 'log-05',
    tanggal: '2026-03-20',
    mingguKe: 4,
    cuaca: 'CERAH',
    jumlahTenagaKerja: { mandor: 1, tukang: 4, laden: 5 },
    uraianPekerjaan: 'Penyelesaian ringbalk timur, perataan dasar lantai rabat beton untuk persiapan keramik',
    progresHariIniPersen: 1.1,
    kendalaDanSolusi: 'Kondisi fisik gedung stabil, elevasi dicek waterpass sesuai bestek.',
    catatanMaterial: 'Pasir pasang habis 1/2 rit, sisa 1/2 rit.',
  },
];

export const INITIAL_WEEKLY_RECAPS: WeeklyRecap[] = [
  {
    mingguKe: 1,
    rentangTanggal: '23 Feb 2026 - 01 Mar 2026',
    targetKumulatif: 12.0,
    realisasiKumulatif: 14.5,
    deviasi: 2.5,
    serapanBiayaKumulatif: 21500000,
    status: 'MENDAHULUI',
    catatanEvaluasi: 'Pekerjaan bongkaran & pondasi berjalan lebih cepat berkat penambahan armada alat bantu.',
  },
  {
    mingguKe: 2,
    rentangTanggal: '02 Mar 2026 - 08 Mar 2026',
    targetKumulatif: 28.0,
    realisasiKumulatif: 30.0,
    deviasi: 2.0,
    serapanBiayaKumulatif: 46200000,
    status: 'MENDAHULUI',
    catatanEvaluasi: 'Pengecoran sloof dan kolom struktur tuntas dengan mutu beton padat.',
  },
  {
    mingguKe: 3,
    rentangTanggal: '09 Mar 2026 - 15 Mar 2026',
    targetKumulatif: 48.0,
    realisasiKumulatif: 51.5,
    deviasi: 3.5,
    serapanBiayaKumulatif: 82100000,
    status: 'MENDAHULUI',
    catatanEvaluasi: 'Dinding hebel terpasang 80% dari total keliling bangunan.',
  },
  {
    mingguKe: 4,
    rentangTanggal: '16 Mar 2026 - 22 Mar 2026',
    targetKumulatif: 64.0,
    realisasiKumulatif: 65.5,
    deviasi: 1.5,
    serapanBiayaKumulatif: 119300000,
    status: 'MENDAHULUI',
    catatanEvaluasi: 'Rangka atap mulai naik, progres fisik unggul +1.5% di atas target rencana jadwal.',
  },
];

export const INITIAL_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'tx-001',
    tanggal: '2026-02-15',
    noBukti: 'BKU/2026/001',
    uraian: 'Penerimaan Dana Revitalisasi Tahap I (70%) dari Kas Bantuan APBN/Pemerintah ke Rekening Bank',
    jenisKas: 'BANK',
    jenisTransaksi: 'PENERIMAAN',
    kategori: 'PENCAIRAN_DANA',
    nominal: 129500000,
    kodeAkun: '4.1.01',
    penerimaAtauPemberi: 'KPPN / Dinas Pemberdayaan Masyarakat',
    keterangan: 'SP2D No: 9942/SP2D/REV/2026',
  },
  {
    id: 'tx-002',
    tanggal: '2026-02-18',
    noBukti: 'BKU/2026/002',
    uraian: 'Penarikan Kas Bank ke Kas Tunai untuk Operasional Lapangan & Belanja Material Tahap Awal',
    jenisKas: 'BANK',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'PENCAIRAN_DANA',
    nominal: 35000000,
    kodeAkun: '1.1.01',
    penerimaAtauPemberi: 'Bendahara TPK (Siti Nurhalizah)',
    keterangan: 'Cek Bank BJB No. BJB-9921',
    linkedDocId: 'tx-003',
    linkedDocType: 'PENCAIRAN_BANK',
  },
  {
    id: 'tx-003',
    tanggal: '2026-02-18',
    noBukti: 'BKT/2026/001',
    uraian: 'Penerimaan Uang Tunai dari Hasil Penarikan Cek Bank BJB No. BJB-9921',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENERIMAAN',
    kategori: 'PENCAIRAN_DANA',
    nominal: 35000000,
    kodeAkun: '1.1.02',
    penerimaAtauPemberi: 'Bank BJB Cab. Cibinong',
    keterangan: 'Saldo awal kas tunai operasional',
    linkedDocId: 'tx-002',
    linkedDocType: 'PENCAIRAN_BANK',
  },
  {
    id: 'tx-004',
    tanggal: '2026-02-20',
    noBukti: 'KWT/REV/2026/02/001',
    uraian: 'Pembayaran Belanja Material Pondasi & Besi Beton (Kwitansi KWT/REV/2026/02/001)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'BELANJA_MATERIAL',
    nominal: 18450000,
    kodeAkun: '5.2.01',
    penerimaAtauPemberi: 'TB. Sumber Jaya Abadi',
    keterangan: 'Semen Gresik 100 sak, Besi 12mm & 8mm, Begel & Kawat bendrat',
    linkedDocId: 'kwt-001',
    linkedDocType: 'KWITANSI',
  },
  {
    id: 'tx-005',
    tanggal: '2026-02-28',
    noBukti: 'SPJ-UPAH/2026/W01',
    uraian: 'Pembayaran Honor Tukang & Laden Harian Minggu Ke-1 (Pekerjaan Pondasi & Galian)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'UPAH_TUKANG',
    nominal: 7200000,
    kodeAkun: '5.2.02',
    penerimaAtauPemberi: 'Mandor Suparman dkk (8 Pekerja)',
    keterangan: 'SPJ Tanda Terima Upah Mingguan 1',
    linkedDocId: 'spj-001',
    linkedDocType: 'PAYROLL_HARIAN',
  },
  {
    id: 'tx-006',
    tanggal: '2026-03-02',
    noBukti: 'BKU/2026/003',
    uraian: 'Penarikan Kas Bank ke Kas Tunai Kedua untuk Pembelian Bata Hebel & Honor Mingguan',
    jenisKas: 'BANK',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'PENCAIRAN_DANA',
    nominal: 40000000,
    kodeAkun: '1.1.01',
    penerimaAtauPemberi: 'Bendahara TPK (Siti Nurhalizah)',
    keterangan: 'Cek Bank BJB No. BJB-9924',
    linkedDocId: 'tx-007',
    linkedDocType: 'PENCAIRAN_BANK',
  },
  {
    id: 'tx-007',
    tanggal: '2026-03-02',
    noBukti: 'BKT/2026/002',
    uraian: 'Penerimaan Uang Tunai dari Penarikan Bank BJB Cek No. BJB-9924',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENERIMAAN',
    kategori: 'PENCAIRAN_DANA',
    nominal: 40000000,
    kodeAkun: '1.1.02',
    penerimaAtauPemberi: 'Bank BJB Cab. Cibinong',
    keterangan: 'Pengisian kas tunai operasional tahap 2',
    linkedDocId: 'tx-006',
    linkedDocType: 'PENCAIRAN_BANK',
  },
  {
    id: 'tx-008',
    tanggal: '2026-03-05',
    noBukti: 'KWT/REV/2026/03/002',
    uraian: 'Pembayaran Belanja Bata Ringan Hebel 7.5cm & Mortar Instan (Kwitansi KWT/REV/2026/03/002)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'BELANJA_MATERIAL',
    nominal: 16800000,
    kodeAkun: '5.2.01',
    penerimaAtauPemberi: 'Distributor Hebel Prima',
    keterangan: 'Hebel 25 m3 + Perekat Mortar 50 sak',
    linkedDocId: 'kwt-002',
    linkedDocType: 'KWITANSI',
  },
  {
    id: 'tx-009',
    tanggal: '2026-03-07',
    noBukti: 'SPJ-UPAH/2026/W02',
    uraian: 'Pembayaran Honor Tukang & Laden Harian Minggu Ke-2 (Pekerjaan Struktur Kolom)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'UPAH_TUKANG',
    nominal: 8100000,
    kodeAkun: '5.2.02',
    penerimaAtauPemberi: 'Mandor Suparman dkk (9 Pekerja)',
    keterangan: 'SPJ Tanda Terima Upah Mingguan 2',
    linkedDocId: 'spj-002',
    linkedDocType: 'PAYROLL_HARIAN',
  },
  {
    id: 'tx-010',
    tanggal: '2026-03-12',
    noBukti: 'KWT/REV/2026/03/003',
    uraian: 'Pembayaran Material Pasir Pasang & Batu Split (Kwitansi KWT/REV/2026/03/003)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'BELANJA_MATERIAL',
    nominal: 6400000,
    kodeAkun: '5.2.01',
    penerimaAtauPemberi: 'Pangkalan Pasir Berkah',
    keterangan: 'Pasir pasang 4 dump truck + Split 2 truck',
    linkedDocId: 'kwt-003',
    linkedDocType: 'KWITANSI',
  },
  {
    id: 'tx-011',
    tanggal: '2026-03-14',
    noBukti: 'BRG/REV/2026/001',
    uraian: 'Pembayaran Uang Muka (Termin 1 - 40%) Borongan Rangka Atap Baja Ringan & Spandek',
    jenisKas: 'BANK',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'UPAH_TUKANG',
    nominal: 13320000,
    kodeAkun: '5.2.02',
    penerimaAtauPemberi: 'CV. Sentosa Baja Mandiri (Mandor Junaedi)',
    keterangan: 'Transfer Bank BJB ke Rekening Kontraktor Borongan',
    linkedDocId: 'brg-001',
    linkedDocType: 'PAYROLL_BORONGAN',
  },
  {
    id: 'tx-012',
    tanggal: '2026-03-15',
    noBukti: 'SPJ-UPAH/2026/W03',
    uraian: 'Pembayaran Honor Tukang & Laden Harian Minggu Ke-3 (Pasangan Bata & Ringbalk)',
    jenisKas: 'TUNAI',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'UPAH_TUKANG',
    nominal: 8550000,
    kodeAkun: '5.2.02',
    penerimaAtauPemberi: 'Mandor Suparman dkk (9 Pekerja)',
    keterangan: 'SPJ Tanda Terima Upah Mingguan 3',
    linkedDocId: 'spj-003',
    linkedDocType: 'PAYROLL_HARIAN',
  },
  {
    id: 'tx-013',
    tanggal: '2026-03-18',
    noBukti: 'BKU/2026/004',
    uraian: 'Biaya Administrasi Bank & Pajak Bunga Tabungan Rekening Revitalisasi',
    jenisKas: 'BANK',
    jenisTransaksi: 'PENGELUARAN',
    kategori: 'PAJAK_RETRIBUSI',
    nominal: 25000,
    kodeAkun: '5.3.01',
    penerimaAtauPemberi: 'Bank BJB',
    keterangan: 'Potongan otomatis rekening koran BJB',
  },
];

export const INITIAL_KWITANSI_LIST: Kwitansi[] = [
  {
    id: 'kwt-001',
    nomorKwitansi: 'KWT/REV/2026/02/001',
    tanggal: '2026-02-20',
    telahTerimaDari: 'Bendahara TPK Program Revitalisasi BUMDes Babakan',
    uangSebanyak: 18450000,
    terbilang: 'Delapan Belas Juta Empat Ratus Lima Puluh Ribu Rupiah',
    untukPembayaran: 'Pembelian Semen Portland, Besi Beton Ulir/Polos, dan Kawat Bendrat Tahap Pondasi',
    penerimaNama: 'TB. Sumber Jaya Abadi (H. Mulyadi)',
    penerimaAlamat: 'Jl. Raya Mayor Oking No. 18, Cibinong',
    tempatTtd: 'Babakan',
    jenisKasPembayaran: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-004',
    status: 'LUNAS',
    progressCategory: 'Pekerjaan Tanah, Pondasi Tapak & Sloof Beton',
    items: [
      {
        id: 'item-1',
        namaBarang: 'Semen Portland Gresik 50 Kg',
        spesifikasi: 'Tipe I SNI',
        volume: 100,
        satuan: 'sak',
        hargaSatuan: 68500,
        subtotal: 6850000,
      },
      {
        id: 'item-2',
        namaBarang: 'Besi Beton Ulir Dia 12 mm SNI',
        spesifikasi: 'Panjang 12 meter standar',
        volume: 60,
        satuan: 'batang',
        hargaSatuan: 125000,
        subtotal: 7500000,
      },
      {
        id: 'item-3',
        namaBarang: 'Besi Beton Polos Dia 8 mm SNI',
        spesifikasi: 'Untuk begel/sengkang',
        volume: 50,
        satuan: 'batang',
        hargaSatuan: 68000,
        subtotal: 3400000,
      },
      {
        id: 'item-4',
        namaBarang: 'Kawat Bendrat Ikat Besi',
        spesifikasi: 'Kawat hitam lentur',
        volume: 28,
        satuan: 'kg',
        hargaSatuan: 25000,
        subtotal: 700000,
      },
    ],
  },
  {
    id: 'kwt-002',
    nomorKwitansi: 'KWT/REV/2026/03/002',
    tanggal: '2026-03-05',
    telahTerimaDari: 'Bendahara TPK Program Revitalisasi BUMDes Babakan',
    uangSebanyak: 16800000,
    terbilang: 'Enam Belas Juta Delapan Ratus Ribu Rupiah',
    untukPembayaran: 'Pembelian Bata Ringan AAC Hebel 7.5 cm dan Mortar Perekat Pasangan Dinding Balai',
    penerimaNama: 'Distributor Hebel Prima (Bpk. Hendra Wijaya)',
    penerimaAlamat: 'Kawasan Industri Sentul, Bogor',
    tempatTtd: 'Babakan',
    jenisKasPembayaran: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-008',
    status: 'LUNAS',
    progressCategory: 'Pekerjaan Kolom, Balok Ring & Dinding Bata Ringan',
    items: [
      {
        id: 'item-5',
        namaBarang: 'Bata Ringan AAC Hebel Tebal 7.5 cm',
        spesifikasi: 'Kualitas Utama Kelas 1 Presisi',
        volume: 24,
        satuan: 'm3',
        hargaSatuan: 550000,
        subtotal: 13200000,
      },
      {
        id: 'item-6',
        namaBarang: 'Semen Mortar Perekat Hebel Thinbed 40 Kg',
        spesifikasi: 'Mortar Utama MU-380',
        volume: 40,
        satuan: 'sak',
        hargaSatuan: 90000,
        subtotal: 3600000,
      },
    ],
  },
  {
    id: 'kwt-003',
    nomorKwitansi: 'KWT/REV/2026/03/003',
    tanggal: '2026-03-12',
    telahTerimaDari: 'Bendahara TPK Program Revitalisasi BUMDes Babakan',
    uangSebanyak: 6400000,
    terbilang: 'Enam Juta Empat Ratus Ribu Rupiah',
    untukPembayaran: 'Pengadaan Agregat Pasir Pasang Ayak dan Batu Split Cor Lantai & Balok',
    penerimaNama: 'Pangkalan Pasir Berkah (Bpk. Rohimat)',
    penerimaAlamat: 'Desa Kadumangu, Babakan Madang',
    tempatTtd: 'Babakan',
    jenisKasPembayaran: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-010',
    status: 'LUNAS',
    progressCategory: 'Pekerjaan Struktur & Dinding',
    items: [
      {
        id: 'item-7',
        namaBarang: 'Pasir Pasang Ayak Kasar Berkualitas',
        spesifikasi: 'Bebas lumpur 1 armada dump truck',
        volume: 3,
        satuan: 'rit/truck',
        hargaSatuan: 1300000,
        subtotal: 3900000,
      },
      {
        id: 'item-8',
        namaBarang: 'Batu Split Cor Ukuran 1/2',
        spesifikasi: 'Batu pecah mesin bersih',
        volume: 2,
        satuan: 'rit/truck',
        hargaSatuan: 1250000,
        subtotal: 2500000,
      },
    ],
  },
];

export const INITIAL_PAYROLL_HARIAN: PayrollHarianBatch[] = [
  {
    id: 'spj-001',
    noSpj: 'SPJ-UPAH/2026/W01',
    periodeAwal: '2026-02-23',
    periodeAkhir: '2026-02-28',
    mingguKe: 1,
    pekerjaanTerkait: 'Pekerjaan Galian Tanah, Pembongkaran Lantai Rusak & Pasangan Pondasi Batu Kali',
    totalDibayarkan: 7200000,
    tanggalBayar: '2026-02-28',
    jenisKas: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-005',
    workers: [
      {
        id: 'w-1',
        nama: 'Suparman',
        peran: 'MANDOR',
        upahHarian: 160000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 25000,
        kasbon: 0,
        totalUpahKotor: 1060000,
        totalUpahBersih: 1060000,
        keterangan: 'Koordinator lapangan',
      },
      {
        id: 'w-2',
        nama: 'Karyo Utomo',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 890000,
        totalUpahBersih: 890000,
        keterangan: 'Tukang batu & pondasi',
      },
      {
        id: 'w-3',
        nama: 'Slamet Riyadi',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 890000,
        totalUpahBersih: 890000,
        keterangan: 'Tukang pembesian',
      },
      {
        id: 'w-4',
        nama: 'Bambang Irawan',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 890000,
        totalUpahBersih: 890000,
        keterangan: 'Tukang bekisting',
      },
      {
        id: 'w-5',
        nama: 'Asep Saepul',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 15000,
        kasbon: 50000,
        totalUpahKotor: 660000,
        totalUpahBersih: 610000,
        keterangan: 'Pembantu tukang',
      },
      {
        id: 'w-6',
        nama: 'Ujang Sasmita',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 660000,
        totalUpahBersih: 660000,
        keterangan: 'Pembantu tukang',
      },
      {
        id: 'w-7',
        nama: 'Jajang Kusuma',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 660000,
        totalUpahBersih: 660000,
        keterangan: 'Pembantu adukan semen',
      },
      {
        id: 'w-8',
        nama: 'Cecep Hidayat',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 4,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 660000,
        totalUpahBersih: 660000,
        keterangan: 'Laden galian tanah',
      },
    ],
  },
  {
    id: 'spj-002',
    noSpj: 'SPJ-UPAH/2026/W02',
    periodeAwal: '2026-03-02',
    periodeAkhir: '2026-03-07',
    mingguKe: 2,
    pekerjaanTerkait: 'Pekerjaan Pengecoran Sloof, Kolom Utama & Mulai Pasang Dinding Hebel',
    totalDibayarkan: 8100000,
    tanggalBayar: '2026-03-07',
    jenisKas: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-009',
    workers: [
      {
        id: 'w-201',
        nama: 'Suparman',
        peran: 'MANDOR',
        upahHarian: 160000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 25000,
        kasbon: 0,
        totalUpahKotor: 1110000,
        totalUpahBersih: 1110000,
      },
      {
        id: 'w-202',
        nama: 'Karyo Utomo',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 930000,
        totalUpahBersih: 930000,
      },
      {
        id: 'w-203',
        nama: 'Slamet Riyadi',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 930000,
        totalUpahBersih: 930000,
      },
      {
        id: 'w-204',
        nama: 'Bambang Irawan',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 930000,
        totalUpahBersih: 930000,
      },
      {
        id: 'w-205',
        nama: 'Asep Saepul',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 690000,
        totalUpahBersih: 690000,
      },
      {
        id: 'w-206',
        nama: 'Ujang Sasmita',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 690000,
        totalUpahBersih: 690000,
      },
      {
        id: 'w-207',
        nama: 'Jajang Kusuma',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 690000,
        totalUpahBersih: 690000,
      },
      {
        id: 'w-208',
        nama: 'Cecep Hidayat',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 690000,
        totalUpahBersih: 690000,
      },
      {
        id: 'w-209',
        nama: 'Dani Ramdan',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 6,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 690000,
        totalUpahBersih: 690000,
      },
    ],
  },
  {
    id: 'spj-003',
    noSpj: 'SPJ-UPAH/2026/W03',
    periodeAwal: '2026-03-09',
    periodeAkhir: '2026-03-14',
    mingguKe: 3,
    pekerjaanTerkait: 'Pemasangan Dinding Bata Hebel & Pengecoran Ringbalk Atas Gedung',
    totalDibayarkan: 8550000,
    tanggalBayar: '2026-03-15',
    jenisKas: 'TUNAI',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-012',
    workers: [
      {
        id: 'w-301',
        nama: 'Suparman',
        peran: 'MANDOR',
        upahHarian: 160000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 25000,
        kasbon: 0,
        totalUpahKotor: 1160000,
        totalUpahBersih: 1160000,
      },
      {
        id: 'w-302',
        nama: 'Karyo Utomo',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 970000,
        totalUpahBersih: 970000,
      },
      {
        id: 'w-303',
        nama: 'Slamet Riyadi',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 970000,
        totalUpahBersih: 970000,
      },
      {
        id: 'w-304',
        nama: 'Bambang Irawan',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 970000,
        totalUpahBersih: 970000,
      },
      {
        id: 'w-305',
        nama: 'Wahyu Hidayat',
        peran: 'TUKANG',
        upahHarian: 135000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 20000,
        kasbon: 0,
        totalUpahKotor: 970000,
        totalUpahBersih: 970000,
      },
      {
        id: 'w-306',
        nama: 'Asep Saepul',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 720000,
        totalUpahBersih: 720000,
      },
      {
        id: 'w-307',
        nama: 'Ujang Sasmita',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 720000,
        totalUpahBersih: 720000,
      },
      {
        id: 'w-308',
        nama: 'Jajang Kusuma',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 720000,
        totalUpahBersih: 720000,
      },
      {
        id: 'w-309',
        nama: 'Dani Ramdan',
        peran: 'LADEN',
        upahHarian: 100000,
        hariKerja: 6,
        jamLembur: 8,
        upahLemburPerJam: 15000,
        kasbon: 0,
        totalUpahKotor: 720000,
        totalUpahBersih: 720000,
      },
    ],
  },
];

export const INITIAL_BORONGAN_LIST: WorkerBoronganItem[] = [
  {
    id: 'brg-001',
    noKontrak: 'SPK-BRG/REV/2026/01',
    namaMandor: 'Mandor Junaedi (CV. Sentosa Baja Mandiri)',
    itemPekerjaan: 'Pekerjaan Rangka Atap Baja Ringan Kanal C75 & Penutup Spandek Pasir 0.35 mm',
    volume: 185,
    satuan: 'm2',
    hargaSatuan: 180000,
    nilaiKontrak: 33300000,
    persentaseSelesai: 40,
    tahapTermin: 'Termin I (Uang Muka 40%)',
    nominalTermin: 13320000,
    tanggalBayar: '2026-03-14',
    status: 'DIBAYAR',
    jenisKas: 'BANK',
    isBookedToBKU: true,
    bkuTransactionId: 'tx-011',
  },
  {
    id: 'brg-002',
    noKontrak: 'SPK-BRG/REV/2026/02',
    namaMandor: 'Mandor Rustam Efendi',
    itemPekerjaan: 'Pekerjaan Pasang Keramik Lantai Granit 60x60 Polished & Plin Lantai',
    volume: 160,
    satuan: 'm2',
    hargaSatuan: 75000,
    nilaiKontrak: 12000000,
    persentaseSelesai: 25,
    tahapTermin: 'Termin I (DP Bahan & Start Kerja 30%)',
    nominalTermin: 3600000,
    tanggalBayar: '2026-03-24',
    status: 'DRAFT',
    jenisKas: 'TUNAI',
    isBookedToBKU: false,
  },
];

export const INITIAL_STANDARD_WAGES: { id: string; role: string; harga: number; desc?: string; satuan?: string }[] = [
  { id: 'w-1', role: 'Mandor Lapangan', harga: 302250, desc: 'Pengawasan teknis & presensi harian', satuan: 'HOK' },
  { id: 'w-2', role: 'Kepala Tukang', harga: 250000, desc: 'Pemimpin kelompok kerja konstruksi', satuan: 'HOK' },
  { id: 'w-3', role: 'Tukang Batu / Kayu / Besi', harga: 200000, desc: 'Tenaga ahli terampil', satuan: 'HOK' },
  { id: 'w-4', role: 'Tukang Cat / Listrik', harga: 200000, desc: 'Tenaga instalasi & finishing', satuan: 'HOK' },
  { id: 'w-5', role: 'Pekerja (Laden / Kenek)', harga: 175000, desc: 'Tenaga pembantu & angkut adukan', satuan: 'HOK' },
];

export const INITIAL_STANDARD_MATERIALS: { id: string; nama: string; satuan: string; harga: number; kategori?: string; spesifikasi?: string }[] = [
  { id: 'm-1', nama: 'Semen PC (50 kg) Tipe I SNI', satuan: 'sak', harga: 75000, kategori: 'STRUKTUR', spesifikasi: 'Semen Gresik / Tiga Roda' },
  { id: 'm-2', nama: 'Bata Merah Bakar Oven Pres', satuan: 'bh', harga: 1000, kategori: 'DINDING', spesifikasi: 'Ukuran standar presisi' },
  { id: 'm-3', nama: 'Hebel / Bata Ringan 7.5 cm', satuan: 'bh', harga: 5500, kategori: 'DINDING', spesifikasi: 'Grade A AAC' },
  { id: 'm-4', nama: 'Hebel / Bata Ringan 10 cm', satuan: 'bh', harga: 7800, kategori: 'DINDING', spesifikasi: 'Grade A AAC' },
  { id: 'm-5', nama: 'Pasir Pasang Bersih', satuan: 'm3', harga: 320000, kategori: 'AGREGAT', spesifikasi: 'Bebas lumpur' },
  { id: 'm-6', nama: 'Pasir Beton Cor', satuan: 'm3', harga: 350000, kategori: 'AGREGAT', spesifikasi: 'Kasar untuk mutu beton' },
  { id: 'm-7', nama: 'Batu Split / Kerikil 2/3 cm', satuan: 'm3', harga: 420000, kategori: 'AGREGAT', spesifikasi: 'Pecah mesin' },
  { id: 'm-8', nama: 'Besi Beton Polos 10 mm SNI', satuan: 'kg', harga: 10500, kategori: 'STRUKTUR', spesifikasi: 'Toleransi 0.2' },
  { id: 'm-9', nama: 'Baja Ringan Profil C 75', satuan: 'btg', harga: 138000, kategori: 'ATAP', spesifikasi: 'Ketebalan 0.75 mm SNI' },
  { id: 'm-10', nama: 'Plafon PVC Lebar 20 cm', satuan: 'm1', harga: 23000, kategori: 'FINISHING', spesifikasi: 'Motif kayu / putih gloss' },
  { id: 'm-11', nama: 'Granit Polish 60x60 cm', satuan: 'm2', harga: 174000, kategori: 'LANTAI', spesifikasi: 'Kualitas 1 Glazed' },
  { id: 'm-12', nama: 'Cat Tembok Interior Vinilex', satuan: 'kg', harga: 30000, kategori: 'FINISHING', spesifikasi: 'Warna standar' },
];

