import { RABMasterItem, RABMaterialComponent } from '../types';

export const INITIAL_RAB_MASTER: RABMasterItem[] = [
  {
    id: 'wbs-1',
    kode: '01.00',
    namaPekerjaan: 'Pekerjaan Persiapan, Pembersihan Lahan & Papan Nama Proyek',
    kategori: 'PERSIAPAN',
    bobotRencana: 4.5,
    progresRealisasi: 4.5,
    volumeRAB: 1,
    satuan: 'Ls',
    biayaRAB: 8325000,
    biayaRealisasi: 8325000,
    materialComponents: [
      {
        id: 'mat-1-1',
        namaMaterial: 'Kayu Kaso 5/7 Kayu Albasia/Lokal',
        satuan: 'btg',
        koefisienPerSatuanPekerjaan: 20,
        hargaSatuan: 28000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-1-2',
        namaMaterial: 'Papan Kayu Terentang 2/20 untuk Bowplank',
        satuan: 'lembar',
        koefisienPerSatuanPekerjaan: 15,
        hargaSatuan: 32000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-1-3',
        namaMaterial: 'Paku Usuk 7-10 cm',
        satuan: 'kg',
        koefisienPerSatuanPekerjaan: 10,
        hargaSatuan: 22000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-1-4',
        namaMaterial: 'Benang Ukur & Terpal Pelindung Proyek',
        satuan: 'roll',
        koefisienPerSatuanPekerjaan: 4,
        hargaSatuan: 75000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'LAINNYA',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-2',
    kode: '02.00',
    namaPekerjaan: 'Pekerjaan Pondasi Batu Belah & Aanstamping',
    kategori: 'PONDASI',
    bobotRencana: 15.5,
    progresRealisasi: 15.5,
    volumeRAB: 54, // 54 m3
    satuan: 'm3',
    biayaRAB: 28675000,
    biayaRealisasi: 28675000,
    materialComponents: [
      {
        id: 'mat-2-1',
        namaMaterial: 'Batu Belah Gunung / Kali 15/20 cm',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 1.2, // 1.2 m3 batu per m3 pondasi
        hargaSatuan: 220000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-2-2',
        namaMaterial: 'Pasir Pasang Kali Progo/Lokal',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 0.52, // 0.52 m3 pasir per m3 pondasi
        hargaSatuan: 250000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-2-3',
        namaMaterial: 'Semen Portland (PC 50kg Tipe I SNI)',
        satuan: 'sak',
        koefisienPerSatuanPekerjaan: 3.2, // ~3.2 sak per m3 pondasi
        hargaSatuan: 68000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-3',
    kode: '03.00',
    namaPekerjaan: 'Pekerjaan Struktur Beton Bertulang (Sloof, Kolom, Balok Praktis)',
    kategori: 'STRUKTUR',
    bobotRencana: 19.0,
    progresRealisasi: 19.0,
    volumeRAB: 32, // 32 m3 beton
    satuan: 'm3',
    biayaRAB: 35150000,
    biayaRealisasi: 35150000,
    materialComponents: [
      {
        id: 'mat-3-1',
        namaMaterial: 'Besi Beton Polos 10 mm SNI (Pancang)',
        satuan: 'btg',
        koefisienPerSatuanPekerjaan: 4.5,
        hargaSatuan: 78000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-3-2',
        namaMaterial: 'Besi Beton Polos 8 mm SNI (Begel / Sengkang)',
        satuan: 'btg',
        koefisienPerSatuanPekerjaan: 3.2,
        hargaSatuan: 54000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-3-3',
        namaMaterial: 'Kawat Bendrat Beton',
        satuan: 'kg',
        koefisienPerSatuanPekerjaan: 0.8,
        hargaSatuan: 25000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-3-4',
        namaMaterial: 'Semen Portland (PC 50kg Tipe I SNI)',
        satuan: 'sak',
        koefisienPerSatuanPekerjaan: 6.8, // mutu K-175 ~ 6.8 sak/m3
        hargaSatuan: 68000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
      {
        id: 'mat-3-5',
        namaMaterial: 'Batu Split / Kerikil Cor 2/3',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 0.82,
        hargaSatuan: 285000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
      {
        id: 'mat-3-6',
        namaMaterial: 'Pasir Beton Cor Ayak Bersih',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 0.54,
        hargaSatuan: 260000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'STRUKTUR',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-4',
    kode: '04.00',
    namaPekerjaan: 'Pekerjaan Pasangan Dinding Bata Ringan (Hebel) & Plester Acian',
    kategori: 'DINDING',
    bobotRencana: 20.0,
    progresRealisasi: 12.0,
    volumeRAB: 280, // 280 m2 dinding
    satuan: 'm2',
    biayaRAB: 37000000,
    biayaRealisasi: 22200000,
    materialComponents: [
      {
        id: 'mat-4-1',
        namaMaterial: 'Bata Ringan AAC (Hebel) Tebal 10 cm (P:60 L:20 T:10)',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 0.1, // 1 m3 untuk ~10 m2 dinding
        hargaSatuan: 620000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'DINDING',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-4-2',
        namaMaterial: 'Semen Mortar Instan Perekat Bata Ringan (Zak 40kg)',
        satuan: 'sak',
        koefisienPerSatuanPekerjaan: 0.25, // 1 sak untuk ~4 m2
        hargaSatuan: 85000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'DINDING',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
      {
        id: 'mat-4-3',
        namaMaterial: 'Semen Plester & Acian Instan (Zak 40kg)',
        satuan: 'sak',
        koefisienPerSatuanPekerjaan: 0.35,
        hargaSatuan: 78000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'FINISHING',
        preferensiHariBeli: 'AKHIR_MINGGU',
      },
      {
        id: 'mat-4-4',
        namaMaterial: 'Pasir Pasang Ayak Halus',
        satuan: 'm3',
        koefisienPerSatuanPekerjaan: 0.03,
        hargaSatuan: 250000,
        tokoDefault: 'TB. Sumber Rejeki Jaya',
        kategoriBahan: 'DINDING',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-5',
    kode: '05.00',
    namaPekerjaan: 'Pekerjaan Rangka Atap Baja Ringan & Penutup Spandek Pasir',
    kategori: 'ATAP',
    bobotRencana: 15.0,
    progresRealisasi: 3.0,
    volumeRAB: 185, // 185 m2 atap
    satuan: 'm2',
    biayaRAB: 27750000,
    biayaRealisasi: 5550000,
    materialComponents: [
      {
        id: 'mat-5-1',
        namaMaterial: 'Kanal C Baja Ringan Zincalume C75.75 SNI',
        satuan: 'btg',
        koefisienPerSatuanPekerjaan: 0.85, // ~0.85 batang per m2 atap
        hargaSatuan: 95000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'ATAP',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-5-2',
        namaMaterial: 'Reng Baja Ringan R30.45 SNI',
        satuan: 'btg',
        koefisienPerSatuanPekerjaan: 1.1,
        hargaSatuan: 48000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'ATAP',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
      {
        id: 'mat-5-3',
        namaMaterial: 'Atap Spandek Berpasir Tebal 0.30 mm',
        satuan: 'lembar',
        koefisienPerSatuanPekerjaan: 0.45,
        hargaSatuan: 110000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'ATAP',
        preferensiHariBeli: 'AKHIR_MINGGU',
      },
      {
        id: 'mat-5-4',
        namaMaterial: 'Baut Roofing & Dynabolt Baja Ringan (Kotak/Dus)',
        satuan: 'dus',
        koefisienPerSatuanPekerjaan: 0.05,
        hargaSatuan: 85000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'ATAP',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-6',
    kode: '06.00',
    namaPekerjaan: 'Pekerjaan Lantai Keramik/Granit 60x60 Polished & Plin Lantai',
    kategori: 'LANTAI',
    bobotRencana: 12.0,
    progresRealisasi: 0.0,
    volumeRAB: 160, // 160 m2 lantai
    satuan: 'm2',
    biayaRAB: 22200000,
    biayaRealisasi: 0,
    materialComponents: [
      {
        id: 'mat-6-1',
        namaMaterial: 'Granit Tile Homogenous 60x60 Glazed Polished (Dus 1.44 m2)',
        satuan: 'dus',
        koefisienPerSatuanPekerjaan: 0.72,
        hargaSatuan: 165000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'LANTAI',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-6-2',
        namaMaterial: 'Semen Mortar Perekat Granit Tile (Zak 25kg)',
        satuan: 'sak',
        koefisienPerSatuanPekerjaan: 0.22,
        hargaSatuan: 92000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'LANTAI',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
      {
        id: 'mat-6-3',
        namaMaterial: 'Semen Oker Pengisi Nat Keramik Tile Grout (Kg)',
        satuan: 'kg',
        koefisienPerSatuanPekerjaan: 0.35,
        hargaSatuan: 18000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'FINISHING',
        preferensiHariBeli: 'AKHIR_MINGGU',
      },
    ],
  },
  {
    id: 'wbs-7',
    kode: '07.00',
    namaPekerjaan: 'Pekerjaan Pengecatan Dinding & Finishing Akhir',
    kategori: 'FINISHING',
    bobotRencana: 6.0,
    progresRealisasi: 0.0,
    volumeRAB: 350, // 350 m2 bidang cat
    satuan: 'm2',
    biayaRAB: 11100000,
    biayaRealisasi: 0,
    materialComponents: [
      {
        id: 'mat-7-1',
        namaMaterial: 'Cat Dinding Interior/Eksterior Weathershield (Pail 20 Kg)',
        satuan: 'pail',
        koefisienPerSatuanPekerjaan: 0.025,
        hargaSatuan: 850000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'FINISHING',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-7-2',
        namaMaterial: 'Cat Dasar Alkali Sealer (Pail 20 Kg)',
        satuan: 'pail',
        koefisienPerSatuanPekerjaan: 0.018,
        hargaSatuan: 720000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'FINISHING',
        preferensiHariBeli: 'AWAL_MINGGU',
      },
      {
        id: 'mat-7-3',
        namaMaterial: 'Roll Cat, Kuas 3", Bak Cat & Amplas Tembok',
        satuan: 'set',
        koefisienPerSatuanPekerjaan: 0.02,
        hargaSatuan: 125000,
        tokoDefault: 'TB. Berkah Sentosa Abadi',
        kategoriBahan: 'FINISHING',
        preferensiHariBeli: 'TENGAH_MINGGU',
      },
    ],
  },
];
